### ISSUE TITLE
ImportError: No module named 'gensim.downloader'

### ISSUE THREAD

**Issue by GraphGrailAi** [RaRe-Technologies/gensim-data#11]
Tried to use code from examples:

```
import gensim.downloader as api
from gensim.models.word2vec import Word2Vec

data = api.load("text8")
```
But got an error:

ImportError: No module named 'gensim.downloader'

**Comment by menshikh-iv** [comment]
@GraphGrailAi This functionality will be available in `gensim>=3.2.0`, please wait for a little bit (several days)

**Comment by sur30** [comment]
Is this functionality available now ?

**Comment by menshikh-iv** [comment]
@sur30 yes, of course!

**Comment by alonsela2015** [comment]
got the same problem. Any idea how to solve?

**Comment by menshikh-iv** [comment]
@alonsela2015 please upgrade your gensim version

**Comment by Bharat-mtr** [comment]
still not wprking in my case

**Comment by NishqR** [comment]
Having this same issue, running the latest version of gensim==4.2.0. Even tried previous versions such as 3.8.1, but with no luck. Anyone got a solution?

**Comment by mpenkov** [comment]
If you think you've found a bug, please open a new ticket and fill in the tempate.
