### ISSUE TITLE
Incorrect outdated link

### ISSUE THREAD

**Issue by aneesh-joshi** [RaRe-Technologies/gensim-data#21]
There seems to be an outdated link here:

https://github.com/RaRe-Technologies/gensim-data/blob/fcc89c2d6832cbf19fdc1b896451dc3432631833/list.json#L105

The wikimedia website seems to have stopped hosting it.
I couldn't figure out the json formatting so didn't make a PR.

**Comment by aneesh-joshi** [comment]
Referring to this link

https://dumps.wikimedia.org/enwiki/20171001

**Comment by menshikh-iv** [comment]
@aneesh-joshi this is OK because we pick data from this link (yes, this doesn't support more by wiki side, but this is fact only).
